# imagem base
FROM python:3.11-slim

# diretório dentro do container
WORKDIR /app

# copiar arquivos
COPY . .

# instalar dependências
RUN pip install --no-cache-dir -r requirements.txt

# expor porta
EXPOSE 8000

# comando de execução
CMD ["gunicorn", "-b", "0.0.0.0:8000", "run:app"]